FROM python:3.12-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# Install dependencies and app code
COPY pyproject.toml .
COPY bot/ bot/
COPY web/ web/
RUN pip install --no-cache-dir .

CMD ["python", "-m", "web"]
