"""add_application_submitted_at

Revision ID: 002
Revises: 001
Create Date: 2026-04-26 14:48:01.453631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###
    op.execute(
        """
        UPDATE applications
        SET submitted_at = created_at
        WHERE status = 'pending'
          AND submitted_at IS NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "submitted_at")
    # ### end Alembic commands ###
