"""Per-model LLM pricing table + cost estimator (T5-04).

Per contracts.md §12.6 ratification — initial Phase 5 pricing:

* ``claude-haiku-4-5-20251001`` — input $1.00, output $5.00 per 1M tokens
* ``gpt-4o-mini`` — input $0.15, output $0.60 per 1M tokens

The gateway (``bot/services/llm_gateway.py::_estimate_cost``) looks up
``MODEL_PRICING`` keyed on ``config.model``. Unknown models raise
``KeyError`` — the gateway categorises this as a structural provider
failure (`emit_stop_signal("llm_provider_structural")`) rather than
crashing.

Quantization: ``estimate_cost`` returns a Decimal at exactly 6 dp so the
NUMERIC(10,6) ledger column accepts it without coercion.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal


@dataclass(frozen=True, slots=True)
class ModelPricing:
    """Per-million-token pricing for a single model id."""

    input_per_million_tokens_usd: Decimal
    output_per_million_tokens_usd: Decimal


MODEL_PRICING: dict[str, ModelPricing] = {
    "claude-haiku-4-5-20251001": ModelPricing(
        input_per_million_tokens_usd=Decimal("1.00"),
        output_per_million_tokens_usd=Decimal("5.00"),
    ),
    "gpt-4o-mini": ModelPricing(
        input_per_million_tokens_usd=Decimal("0.15"),
        output_per_million_tokens_usd=Decimal("0.60"),
    ),
    # DeepSeek official API pricing checked 2026-07-14. Cache-hit input is
    # cheaper, but the ledger deliberately estimates every input token at the
    # conservative cache-miss rate.
    "deepseek-v4-flash": ModelPricing(
        input_per_million_tokens_usd=Decimal("0.14"),
        output_per_million_tokens_usd=Decimal("0.28"),
    ),
    "deepseek-v4-pro": ModelPricing(
        input_per_million_tokens_usd=Decimal("0.435"),
        output_per_million_tokens_usd=Decimal("0.87"),
    ),
    "gpt-5-mini": ModelPricing(
        input_per_million_tokens_usd=Decimal("0.25"),
        output_per_million_tokens_usd=Decimal("2.00"),
    ),
    "gpt-5.4-nano": ModelPricing(
        input_per_million_tokens_usd=Decimal("0.20"),
        output_per_million_tokens_usd=Decimal("1.25"),
    ),
    "gpt-5-nano": ModelPricing(
        input_per_million_tokens_usd=Decimal("0.05"),
        output_per_million_tokens_usd=Decimal("0.40"),
    ),
    # OpenAI model catalog, verified 2026-07-16: $0.02 / 1M input tokens.
    "text-embedding-3-small": ModelPricing(
        input_per_million_tokens_usd=Decimal("0.02"),
        output_per_million_tokens_usd=Decimal("0"),
    ),
}


def estimate_cost(*, model: str, tokens_in: int, tokens_out: int) -> Decimal:
    """Look up ``MODEL_PRICING`` by ``model`` and compute cost.

    Parameters
    ----------
    model:
        Provider-specific model id; must be a key of ``MODEL_PRICING``.
    tokens_in:
        Input/prompt tokens consumed by the call.
    tokens_out:
        Output/completion tokens generated by the call.

    Returns
    -------
    Decimal
        Cost in USD, quantized to 6 decimal places (matches
        ``llm_usage_ledger.cost_usd NUMERIC(10, 6)``).

    Raises
    ------
    KeyError
        If ``model`` is not a key of ``MODEL_PRICING``. The gateway treats
        this as a configuration / structural error.
    """
    pricing = MODEL_PRICING[model]
    cost_in = (pricing.input_per_million_tokens_usd * Decimal(tokens_in)) / Decimal(1_000_000)
    cost_out = (pricing.output_per_million_tokens_usd * Decimal(tokens_out)) / Decimal(1_000_000)
    return (cost_in + cost_out).quantize(Decimal("0.000001"))


__all__ = ["MODEL_PRICING", "ModelPricing", "estimate_cost"]
